services:
  gost:
    image: gogost/gost
    container_name: gostv3
    volumes:
      - ./dist/config/gost/config.yaml:/etc/gost/config.yaml
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/gost/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/gost/privkey.pem
    network_mode: 'host'
    command: ['-C', '/etc/gost/config.yaml', '-D']
    restart: unless-stopped
    env_file:
      - .env

  network-mall-gost:
    image: network-mall-gost-${ENV}
    container_name: network-mall-gost-${ENV}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '30000:30000'
    depends_on:
      gost:
        condition: service_healthy # 等待 gost 服务健康检查通过
