version: '3.8'

services:
  gost:
    image: gogost/gost
    container_name: gostv3
    volumes:
      # TODO
      - ./dist/config/config.yaml:/etc/gost/config.yaml
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/gost/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/gost/privkey.pem
    network_mode: 'host'
    command: ['-C', '/etc/gost/config.yaml', '-D']
    restart: unless-stopped
