# 动态配置，每个用户都起一个  service
# 通过 service 区分不同用户
services:
- name: service-30002
  addr: :30002
  # limiter: limiter-1
  # observer: observer-0 # 服务上的观测器
  handler:
    type: http2
    observer: observer-0 # handler 上的观测器
    auther: auther-0
    metadata:
      enableStats: true # 开启统计
      observePeriod: 5s
  listener:
    type: http2
  metadata:
    knock: www.google.com
    probeResist: file:/var/www/html/index.html
    enableStats: true # 开启统计
    observePeriod: 5s

observers:
- name: observer-0
  plugin:
    type: http
    addr: http://127.0.0.1:30000/observer
    timeout: 10s

tls:
  certFile: /etc/gost/fullchain.pem
  keyFile: /etc/gost/privkey.pem


authers:
- name: auther-0
  plugin:
    type: http
    addr: http://127.0.0.1:30000/auth

api:
  addr: 0.0.0.0:30001
  pathPrefix: /api
  accesslog: true
  auth:
    username: admin
    password: adminadmin
